### ISSUE TITLE
.help [command] not working properly

### ISSUE THREAD

**Issue by fsk10** [dzejkob-b/discord_irc_pugbot#12]
The help syntax to show help-information for a specific command does not display any information other than the default .help output.

Description of the command on the github page:
help - Shows help information. Usage: !help [command]

**Comment by dzejkob-b** [comment]
Incorrectly documented - .help is only customizable text message (better to see some user-friendly msg). The correct command is .command / .command [cmd]. + list of all commands replaced by link to project homepage / documentation.
