### ISSUE TITLE
Changes to captain votes

### ISSUE THREAD

**Issue by fsk10** [dzejkob-b/discord_irc_pugbot#13]
Reduce the votes to 1 vote per player in the puglist.
A player who has voted should not be able to recast his vote without first using the command to unvote.

It would also be good to have the option to disable captain votes entirely.
(if a better captain picking system is implemented the votes might not be needed/wanted)

**Comment by dzejkob-b** [comment]
The voting was reduced to one vote + when the pug starting, the player cannot revote/unvote.

Still not configurable.

**Comment by oreleraki** [comment]
Instead of unvote + and then vote which is a bit tiresome.

**Proposed**
1
.vote player-name
Initial voting
.switchvote player-name
Only allow if you voted before.
2.
.vote player-name
Will only overwrite the previous vote to the current.

Your thoughts ?

**Comment by dzejkob-b** [comment]
The .unvote command only remove votes - is only used to remove all player votes. The second scenario is allreay implemented - each .vote pick new player to vote and removes the other one to the number of pug possible votes. (the revote/unvote is possible only until pug is not filled). Dunno if switchvote will be more readable - the players dont voting much anyway.

Acually is needed to add some .updatepug ctf setMaxVotes 0-x with possibility to set 0 - pug voting off.

(+ other settings changes follows)

**Comment by dzejkob-b** [comment]
Turn off votes is now possible under .setpugconfig command (set votes to zero).
