### ISSUE TITLE
Cannot exclude a command for a specific channel

### ISSUE THREAD

**Issue by fsk10** [dzejkob-b/discord_irc_pugbot#17]
The command to exclude/delete a command for a specific channel does not work.

!addcmd spam::rule1 ::DELETE
If I use the above example it would just add the text "::DELETE" for the .rule1 output

**Comment by dzejkob-b** [comment]
Fixed the ::DELETE thing + its now possible to remove some specific rule in some channel. In that scenario there will be gap like rule1, rule3, rule6 etc. but it displays all possible rules.
