### ISSUE TITLE
Incorrectly displayed output for the quickpug "removed for inactivity"

### ISSUE THREAD

**Issue by fsk10** [dzejkob-b/discord_irc_pugbot#18]
At 2020-06-02 04:10 the bot removed a tdm quickpug for inactivity, but the output from the bot was:
"The [object Object] pug was removed for inactivity."

![Removed_for_inactivity](https://user-images.githubusercontent.com/65980437/83489883-6ccfa100-a4af-11ea-8889-bc3ad92a1b7c.png)

**Comment by dzejkob-b** [comment]
Fixed.
