### ISSUE TITLE
Improved captain picking system

### ISSUE THREAD

**Issue by fsk10** [dzejkob-b/discord_irc_pugbot#3]
When the PUGBOT picks random captains it should prioritize players close to each other in average-pick stats.
The bot should not set "new players" as random captains [less than x pugs played]

**Comment by dzejkob-b** [comment]
Added captain pick priority based on avg-pick. The relevant data is shown under .avgpick command - it shows how the joined players are averagely picked. Problem might be, that frequently picked players remains as captain all the time (if they dont have nocapt tag). Become captain is not scored as firstpick - its just +1 captain (so it just not modify the pick statistic).

Still not ideal - keeping opened.

**Comment by dzejkob-b** [comment]
Updated that first pick is completely random and the rest captains is the minimal avg-pick difference from the first one. If the first captain was wanted captain by .captain, or if first captain was voted one, the logic is same.

**Comment by fsk10** [comment]
* The picking of random captains should never pick players that have avgpick stats of 6 or above.

* The bot should never pick new players as captain that have played less then 10 pugs.
<If a new player joins and plays two pugs where his avgpick stats becomes 4.0, he should still not be picked as a random captain until he has played 10 pugs. If he wants to become captain he can still manually force it with .captain"

**Comment by dzejkob-b** [comment]
Updated to-segment captain picking - first segment is players with >= 10 pugs + avgpick stats <= 6 and second segment with the rest. It prefer captains from the first segments, but if no such player, it picks from second segment.

Logic is still based on old stats. Will be changed + will be configurable.

**Comment by dzejkob-b** [comment]
Implemented avgpicks from new statistics. Might be shown by this command:

.avgpickspec ctf method:pastdays30 lockpick humak blz

which shows avg-pick stats by specified method and list of players. Posible methods are: sumarize (curently default), pastdays30 (stats from past x days), pastpicks30 (stats of past x picks)

Currently default is sumarize (old sumarize stats) which applied from captain picking decision. To change wanted avg-pick stats method use for example: !setpugconfig ctf avgpickmth pastdays30
