### ISSUE TITLE
.j should always let you join the ctf pug

### ISSUE THREAD

**Issue by HUMAKOVIC** [dzejkob-b/discord_irc_pugbot#31]
When a quickpug is created, '.j' does not work.

Writing .j should always let the player join ctf pug.

**Comment by oreleraki** [comment]
does `.join` works ? and does '.j [pug-name]' work as well ?

**Comment by HUMAKOVIC** [comment]
.join does not work either.

Only '.j ctf' works

**Comment by oreleraki** [comment]
Ok, this probably by design, because there is more then 1 pug.
Maybe adding a `.configpug default [pug-name]`
Which will direct all pug commands to the default pug, if no specific pug specify.
Sounds good ?

**Comment by fsk10** [comment]
> Ok, this probably by design, because there is more then 1 pug.
> Maybe adding a `.configpug default [pug-name]`
> Which will direct all pug commands to the default pug, if no specific pug specify.
> Sounds good ?

I think it should be channel specific in that case (maybe what you meant).
So in #pugs channel we can set CTF as default, and in #spam we can set one of those pugs as default.
We dont want it to be "global" so that if you type .j in #spam you get added to CTF in #pugs :)

**Comment by fsk10** [comment]
After some discussions and insight in how others handle the same scenario/task it would be preferable if every user can set their own default pug for each pug-channel.
i.e. In the #ctf channel a user can type `.setdefault utplus` and it will always join the utplus pug when that user types `,j` in the #ctf channel, while a different user has their default set to the ctf pug instead when typing `.j`.

**Comment by oreleraki** [comment]
The following behavior was implemented

**Name:** Default Pickup per Channel.
**Scope:** Per Channel
**Configuration Scope:** Pug Configuration
**ConfigurationPug Name:** "isdefault"
**Possible Values:** true, false[default]
**Description:**
On channels that have 2+ pickup lists, when a user execute commands `join` or `leave` it will execute it on a pickup that has the "_isDefault_" setting marked as **true**.

**Comment by oreleraki** [comment]
**Name:** Default Pickup per Channel.
**Scope:** Per Channel
**Configuration Scope:** Pug Configuration
**ConfigurationPug Name:** "isdefault"
**Possible Values:** true, false[default]
**Description:**
On channels that have 2+ pickup lists, when a user execute commands join or leave it will execute it on a pickup that has the "isDefault" setting marked as true.
