### ISSUE TITLE
nick refresh in stats

### ISSUE THREAD

**Issue by dzejkob-b** [dzejkob-b/discord_irc_pugbot#47]
Hodor at 9:00 PM
hey mixeh
Blue Team: ALEX, clinic, sekomaniac, HEKTOR, flaskk
why i am with nick HEKTOR with capital letters there
if my discord user name is Hodor?
its really annoying

**Comment by oreleraki** [comment]
Not sure this is still happening or relevant.

**Comment by oreleraki** [comment]
Closed, Hodor reports it's working well.
