### ISSUE TITLE
Rejoin-PUG cooldown

### ISSUE THREAD

**Issue by fsk10** [dzejkob-b/discord_irc_pugbot#5]
Option to enable/disable cooldown feature to rejoin pug if you .leave
- Player can't rejoin pug for x minutes (defined by admin-setting)
- PUGBOT msg something like: "Cooldown: You have to wait <x> minutes to join the pug again"

This should be implemented after (or at the same time) as the "Improved captain picking system" and "Idle captain ban" features.

**Comment by dzejkob-b** [comment]
Implemented rejoin timeout - the default is 30 sec (currently not configurable). Admin may delete player from pug with specific timeout.

Still not ideal - keeping opened.

**Comment by HUMAKOVIC** [comment]
Right now the cooldown is whenever someone leaves the pug. It should only be after captains have been picked.

Also, the .lva command does not give any cooldown. And please change the default to 5 minutes.
