### ISSUE TITLE
Player leave/join cooldown should only be enforced when pug has been filled

### ISSUE THREAD

**Issue by fsk10** [dzejkob-b/discord_irc_pugbot#76]
If the pug has not been filled it should not enforce the player cooldown if a player leave/rejoin the pug.
This should only be enforced when a pug has been filled with 10 players and captains have been picked.

![player_cooldown_bug](https://user-images.githubusercontent.com/65980437/88660197-933c4200-d0d6-11ea-9de1-72f0bfa4e82f.png)

**Comment by oreleraki** [comment]
The issue starts when bot starts up and first pickup is filled. from that point onward the cooldown mechanism kicked in, because it didn't detected the pickup is already over. thus every time someone left it gave him a cooldown.
Now it should be resolved.

**Comment by fsk10** [comment]
We are again seeing issues with player cooldown when player leaves/rejoin the pug even though the pug has not filled and captains been picked.

![player_cooldown_problem](https://user-images.githubusercontent.com/65980437/91705227-f9f0c780-eb7c-11ea-8194-a57071e8912b.png)

**Comment by fsk10** [comment]
This issue has been fixed by @anze-k
