### ISSUE TITLE
Captain votes allowed even when setting is turned off

### ISSUE THREAD

**Issue by fsk10** [dzejkob-b/discord_irc_pugbot#83]
It now looks like the captain votes work again, even though the setting is still turned off in the pugconfig.
It also allows captain votes while the pug isnt even filled, which seems to be incorrect as well.

![pugconfig-ctf-votes](https://user-images.githubusercontent.com/65980437/93028995-33fba800-f618-11ea-81a8-21099b3f1dcf.png)

![votes_bug](https://user-images.githubusercontent.com/65980437/93029000-36f69880-f618-11ea-94ef-c747b4a61584.png)

**Comment by oreleraki** [comment]
@fsk10 Please tell me when you ready for testing
